-- ============================================================================
-- 02_RAW_TABLES.SQL — Raw tables for Nickel Trading & Market Intelligence
-- ============================================================================
USE DATABASE NICKEL_TRADING;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE RAW.TRADES (
  ID VARCHAR DEFAULT UUID_STRING(),
  DATA VARIANT,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.MARKET_PRICES (
  ID VARCHAR DEFAULT UUID_STRING(),
  DATA VARIANT,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.SUPPLY_DEMAND (
  ID VARCHAR DEFAULT UUID_STRING(),
  DATA VARIANT,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.POSITIONS (
  ID VARCHAR DEFAULT UUID_STRING(),
  DATA VARIANT,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.MARKET_RESEARCH (
  ID VARCHAR DEFAULT UUID_STRING(),
  DATA VARIANT,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.BUYER_CONTRACTS (
  ID VARCHAR DEFAULT UUID_STRING(),
  DATA VARIANT,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

