-- ============================================================================
-- 02_RAW_TABLES.SQL - Domain-specific typed table schemas
-- ============================================================================
USE DATABASE MINING_NICKEL_TRADING;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE RAW.MINES (
  MINE_ID VARCHAR(20) NOT NULL, MINE_NAME VARCHAR(200), PROVINCE VARCHAR(50), MINE_TYPE VARCHAR(30), CAPACITY_TPD FLOAT, GRADE_NI_PCT FLOAT, STATUS VARCHAR(20), OPENED_DATE DATE, CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.PRODUCTION_BATCHES (
  BATCH_ID VARCHAR(30) NOT NULL, MINE_ID VARCHAR(20), BATCH_DATE DATE, ORE_TONNES FLOAT, NI_GRADE_PCT FLOAT, RECOVERY_RATE FLOAT, OUTPUT_TONNES FLOAT, PROCESSING_COST FLOAT, STATUS VARCHAR(20), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.SHIPMENTS (
  SHIPMENT_ID VARCHAR(30) NOT NULL, ENTITY_ID VARCHAR(20), DESTINATION VARCHAR(100), SHIP_DATE DATE, QUANTITY FLOAT, UNIT VARCHAR(10), PRICE_PER_UNIT FLOAT, TOTAL_VALUE FLOAT, CARRIER VARCHAR(50), STATUS VARCHAR(20), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.QUALITY_TESTS (
  TEST_ID VARCHAR(30) NOT NULL, ENTITY_ID VARCHAR(20), TEST_DATE TIMESTAMP, TEST_TYPE VARCHAR(50), PARAMETER VARCHAR(50), VALUE FLOAT, THRESHOLD FLOAT, RESULT VARCHAR(20), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);
