-- Generated from generator/demo_specs/aws-indonesia-mining-nickel-trading.json
-- Regenerate with: python3 generator/gen_repo_docs.py aws-indonesia-mining-nickel-trading
-- This is the schema that is actually deployed for ID_MINING_NICKEL_TRADING.

-- Alerts fire on the bottom tail of Avg Ni Price
-- (lower is worse for this metric).
CREATE OR REPLACE DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
WITH thresh AS (
  SELECT PERCENTILE_CONT(0.09) WITHIN GROUP (ORDER BY KPI_AVG_NI_PRICE) AS T
  FROM RAW.MARKET_PRICES
)
SELECT
  e.ID AS ENTITY_ID,
  e.NAME AS ENTITY_NAME,
  e.REGION,
  e.CATEGORY,
  e.STATUS,
  COUNT(*) AS EVENT_COUNT,
  SUM(CASE WHEN f.KPI_AVG_NI_PRICE <= (SELECT T FROM thresh) THEN 1 ELSE 0 END) AS ALERT_COUNT,
  ROUND(AVG(f.KPI_AVG_NI_PRICE), 2) AS AVG_NI_PRICE,
  ROUND(AVG(f.KPI_LME_FORECAST_30D), 2) AS AVG_LME_FORECAST_30D,
  ROUND(AVG(f.KPI_CHINA_PREMIUM), 2) AS AVG_CHINA_PREMIUM,
  ROUND(AVG(f.KPI_EV_DEMAND_INDEX), 2) AS AVG_EV_DEMAND_INDEX,
  ROUND(AVG(f.KPI_HPM_COMPLIANCE), 2) AS AVG_HPM_COMPLIANCE
FROM RAW.MARKET_PRICES f
JOIN RAW.BUYER_CONTRACTS e ON e.ID = f.ENTITY_ID
CROSS JOIN thresh
GROUP BY e.ID, e.NAME, e.REGION, e.CATEGORY, e.STATUS;

CREATE OR REPLACE DYNAMIC TABLE CURATED.TREND_ANALYSIS
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT
  f.EVENT_DATE AS METRIC_DATE,
  COUNT(*) AS EVENT_COUNT,
  ROUND(AVG(f.KPI_AVG_NI_PRICE), 2) AS AVG_NI_PRICE,
  ROUND(AVG(f.KPI_LME_FORECAST_30D), 2) AS AVG_LME_FORECAST_30D,
  ROUND(AVG(f.KPI_CHINA_PREMIUM), 2) AS AVG_CHINA_PREMIUM,
  ROUND(AVG(f.KPI_EV_DEMAND_INDEX), 2) AS AVG_EV_DEMAND_INDEX,
  ROUND(AVG(f.KPI_HPM_COMPLIANCE), 2) AS AVG_HPM_COMPLIANCE
FROM RAW.MARKET_PRICES f
GROUP BY f.EVENT_DATE;

-- DISPLAY is rendered here so it is byte-identical to the card the app
-- was designed with (asserted by the round-trip check in kpi_parse.py).
CREATE OR REPLACE DYNAMIC TABLE CURATED.KPI_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS WITH ev AS (SELECT AVG(KPI_AVG_NI_PRICE) AS KPI_AVG_NI_PRICE, AVG(KPI_HPM_COMPLIANCE) AS KPI_HPM_COMPLIANCE, AVG(KPI_LME_FORECAST_30D) AS KPI_LME_FORECAST_30D, AVG(KPI_CHINA_PREMIUM) AS KPI_CHINA_PREMIUM, AVG(KPI_EV_DEMAND_INDEX) AS KPI_EV_DEMAND_INDEX FROM RAW.MARKET_PRICES),
     en AS (SELECT SUM(KPI_REVENUE_MTD) AS KPI_REVENUE_MTD, SUM(KPI_CONTRACTS_ACTIVE) AS KPI_CONTRACTS_ACTIVE FROM RAW.BUYER_CONTRACTS)
  SELECT 1 AS SORT_ORDER, 'Revenue (MTD)' AS TITLE, KPI_REVENUE_MTD AS VALUE_NUM, 'US$' || TO_VARCHAR(CAST(ROUND(((KPI_REVENUE_MTD) / 1000000)) AS DECIMAL(38,0))) || 'M' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 2 AS SORT_ORDER, 'Avg Ni Price' AS TITLE, KPI_AVG_NI_PRICE AS VALUE_NUM, '$' || LTRIM(TO_VARCHAR(CAST(ROUND((KPI_AVG_NI_PRICE)) AS DECIMAL(38,0)), '999,999,999,999')) || '/t' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 3 AS SORT_ORDER, 'Contracts Active' AS TITLE, KPI_CONTRACTS_ACTIVE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_CONTRACTS_ACTIVE)) AS DECIMAL(38,0))) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 4 AS SORT_ORDER, 'HPM Compliance' AS TITLE, KPI_HPM_COMPLIANCE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_HPM_COMPLIANCE)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 5 AS SORT_ORDER, 'LME Forecast (30d)' AS TITLE, KPI_LME_FORECAST_30D AS VALUE_NUM, '$' || LTRIM(TO_VARCHAR(CAST(ROUND((KPI_LME_FORECAST_30D)) AS DECIMAL(38,0)), '999,999,999,999')) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 6 AS SORT_ORDER, 'China Premium' AS TITLE, KPI_CHINA_PREMIUM AS VALUE_NUM, '+' || '$' || TO_VARCHAR(CAST(ROUND((KPI_CHINA_PREMIUM)) AS DECIMAL(38,0))) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 7 AS SORT_ORDER, 'EV Demand Index' AS TITLE, KPI_EV_DEMAND_INDEX AS VALUE_NUM, '↑' || ' ' || TO_VARCHAR(CAST(ROUND((KPI_EV_DEMAND_INDEX)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en;

ALTER DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.TREND_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE CURATED.KPI_SUMMARY SUSPEND;
