-- ============================================================================
-- 99_RESET.SQL — Reset Nickel Trading & Market Intelligence to clean demo state
-- ============================================================================
USE DATABASE NICKEL_TRADING;

-- Suspend tasks during demo
ALTER TASK IF EXISTS APP.TASK_INGEST_LME SUSPEND;
ALTER TASK IF EXISTS APP.TASK_REFRESH_POSITIONS SUSPEND;
ALTER TASK IF EXISTS APP.TASK_FORECAST_PRICES SUSPEND;

-- Force refresh Dynamic Tables
ALTER DYNAMIC TABLE CURATED.POSITION_BOOK REFRESH;
ALTER DYNAMIC TABLE CURATED.FORWARD_CURVE REFRESH;
ALTER DYNAMIC TABLE CURATED.SUPPLY_DEMAND_BALANCE REFRESH;
ALTER DYNAMIC TABLE CURATED.CONTRACT_EXPOSURE REFRESH;

-- Verify key demo numbers
-- SELECT COUNT(*) FROM NICKEL_TRADING.RAW.TRADES → 8000
-- SELECT COUNT(*) FROM NICKEL_TRADING.RAW.MARKET_PRICES → 300000
-- SELECT COUNT(*) FROM NICKEL_TRADING.RAW.SUPPLY_DEMAND → 5000

-- Resume tasks
ALTER TASK IF EXISTS APP.TASK_FORECAST_PRICES RESUME;
ALTER TASK IF EXISTS APP.TASK_REFRESH_POSITIONS RESUME;
ALTER TASK IF EXISTS APP.TASK_INGEST_LME RESUME;
